data/science/hail_size.json

Adapted from http://www.spc.noaa.gov/misc/tables/hailsize.htm

hail size analogs from NOAA

---

data/geography/london_underground_stations.json

Includes lines and Travelcard zones for each station.

Add London Underground stations

---

data/words/eggcorns.json

Fixed a couple mistakes in the first pass and added "sneak peak/peek". Thanks for merging!

Eggcorns 2

---

data/geography/oceans.json

Pulled from Wikipedia, this list contains the oceans, and a
comprehensive list of "seas". Thorough, but not too large.

Oceans and seas of the world

---

data/colors/paints.json

Closes #81
File was generated [using paint color data](https://docs.google.com/spreadsheets/d/1_Sjj747b2P66p6H2U--sEG34ymXjsKlC-2ujZYs3Qmk/edit?usp=sharing) collected by @luismqueral and converted to a manage-sized JSON file [using a quick ruby script](https://gist.github.com/metavida/231aa93f4207ff84c84d#file-create_paint_json-rb)

Paint colors from a few different brands

---

data/words/spells.json

new data, a list of harry potter spells.
some data from [here](http://www.pojo.com/harrypotter/spelist.shtml), but the page is no longer copyrighted and i can't find a way of contacting the author.

added a list of harry potter spells and descriptions

---

README.md

i think when i first made this i tweeted about it once and then let it languish on a free heroku dyno forever. 
i bet i didn't even hashtag it botally.

add corpora-api project

---

data/foods/vegetable_cooking_times.json

add list of vegetable cooking times

---

data/medicine/diagnoses.json

This PR adds a few hundred of the approximately 43,000 codes from the [International Classification of Diseases, Tenth Revision, Clinical Modification](http://www.cdc.gov/nchs/icd/icd10cm.htm) used to categorize diseases, injuries, and other medical conditions. These come from a file from the Centers for Disease Control, so I figure it's free to use.

Add a subset of ICD-10-CM medical codes and descriptions

---

data/words/spells.json

I changed the object keys for the Harry Potter spells to make them easier to use, esp. with JavaScript. Also, fixed a number of inconsistencies with capitalization, verb tense, and punctuation.

Spells: Fix inconsistencies, etc.

---

data/sports/nfl_teams.json

Thought a sports section might be handy. Here's a list of NFL teams, their locations, and their stadiums.

Adding NFL teams.

---

data/music/rock_hall_of_fame.json

All artists who have been inducted into the Rock N Roll Hall of Fame. Fun for trivia!

Added rock hall of fame artists

---

data/technology/computer_sciences.json

Added the "Swift" programming language to the computer_sciences.json file.

Added Swift programming language

---

data/games/bannedGames/argentina/bannedList.json
data/games/bannedGames/brazil/bannedList.json
data/games/bannedGames/china/bannedList.json
data/games/bannedGames/denmark/bannedList.json

This commit will add a list of banned games, categorized by country. The list is not yet complete, and only includes the following countries:
1. Argentina
2. Brazil
3. China
4. Denmark
More countries will be added over time.

Added list of banned games

---

data/animals/dogs.json

Missing dog

---

data/divination/tarot_interpretations.json

from Mark McElroy's [A Guide to Tarot Meanings](http://www.madebymark.com/a-guide-to-tarot-card-meanings/)
Text on that page and in the document indicates that it is in the public domain.
(Adding a new top-level category because this data didn't seem to fit into any of the others; tarot is not "mythology," "archetypes," "science," etc. I'm hoping that with the addition of this category others will add corpora for astrology, I Ching, and whatever other divination methods, metaphysics and esoterica)

tarot interpretations

---

data/technology/social_networking_websites.json

`"Meetup (website)",` -> `"Meetup",`

Little clean up

---

data/music/hamilton_musical_obcrecording_actors_characters.json

Fixed by putting into /data/music. Thanks, Darius!
===
Actors and the named characters played by them in the Original Broadway Cast recording of Hamilton. Actors who played multiple characters are listed multiple times. Pulled from: https://en.wikipedia.org/wiki/Hamilton_(musical)#Principal_roles_and_major_casts. From my #ham4corpus repo (https://github.com/amandavisconti/ham4corpus).

Hamilton musical OBC recording actors & characters

---

data/words/compounds.json

I created this list for my [@novelcompounds bot](https://twitter.com/novelcompounds) ([source code](https://github.com/matthewmcvickar/novel-compounds-bot)). It may be useful to others!
I consent to attribution.

Add list of compound words.

---

data/divination/zodiac.json

Added divination/zodiac.json for Western and Eastern (Chinese) zodiac signs and information.
Ran through JSONLint and confirmed valid.

Added Western and Eastern (Chinese) Zodiac

---

data/geography/canadian_municipalities.json

I was using these for a project in conjunction with some other data already in corpora so I figured I'd contribute them.

Add top 100 Canadian municipalities by 2011 population

---

data/humans/2016_us_presidential_candidates.json

All individuals who filed a Statement of Candidacy with the FEC to register as a presidential candidate in the 2016 United States election. Scraped from: http://www.fec.gov/press/resources/2016presidential_form2pty.shtml

2016 us presidential candidates

---

data/divination/tarot_interpretations.json

The source document includes "fortune telling" sentences for each card. I'd originally excluded these from my scraper code but later found I needed them for a project. So here's a revised version of the file with changes included!

updated w/"fortune telling" sentences from source

---

data/humans/norwayFirstNamesBoys.json

Fix typo from PR https://github.com/dariusk/corpora/pull/194.

Fix girls->boys typo

---

data/animals/birds_north_america.json

Made additions and deletions to birds_north_america according to most recent ABA checklist.

Update per ABA Checklist Version 7.9.0 – July 2016

---

data/plants/plants.json

Add list of plants by common name

---

data/sports/nfl_teams.json

http://www.chargers.com/news/2017/01/12/chargers-relocate-los-angeles

San Diego Chargers -> Los Angeles Chargers

---

data/religion/christian_saints.json

Googled each altered name to confirm the new spelling is correct.

Fix encoding errors in religion/christian_saints

---

data/technology/new_technologies.json

Spelling correction in technology/new_technologies.json

'currencoes' -> 'currencies'

---

data/geography/nyc_neighborhood_zips.json

There may be a better source of NYC neighborhood names but I don't think anybody has correlated with ZIP codes

NYC neighborhoods and ZIP codes

---

README.md

fixed the markdown layout by adding necessary spaces

fixed the markdown layout by adding necessary spaces

---

data/objects/corpora_winners.json

* Add deities and supernatural creatures winner
* Update elements winner for 2017

Update corpora winners

---

data/foods/fruits.json
data/foods/vegetables.json

tomato is a fruit

---

data/geography/japanese_prefectures.json

I made a JSON file about Japanese areas and prefectures.

add Japanese prefectures info

---

data/film-tv/iab_categories.json

could be of use for people making mockups or data into the advertising / TV business. I use it at least :)

added categories from Interactive Advertising Bureau

---

data/geography/sf_neighborhoods.json

This is a list of San Francisco neighborhoods and their centers. I had used it for a previous project, thought it might be helpful for others.

added sf neighborhoods json file

---

data/words/harvard_sentences.json

Changed "ii cloud of dust stung his tender eyes." to "A cloud of dust stung his tender eyes.".

Fixed Typo

---

data/film-tv/look-around-you-shakespeare.json

Adding the complete works of Shakespeare (according to Look Around You).
Checked against this video: https://www.youtube.com/watch?v=g7JrUGhfcTI

Add Shakespeare plays according to Look Around You

---

data/plants/plants.json

Makes automatic loading easier -- believe "instrument" was a mistake in the first place

Fix list name for consistency with file name/topic

---

data/colors/wikipedia.json

Parsed 1017 colors from [https://en.wikipedia.org/wiki/Lists_of_colors](https://en.wikipedia.org/wiki/Lists_of_colors)

1017 color names and values from Wikipedia

---

data/divination/zodiac.json

Here are some personality keywords for western zodiac signs, identified in consultation with Sabrina Banes. (I always need this kind of thing when talking about astrology, but I couldn't find an easy listing that is also CC0 licensed.)

Zodiac keywords

---

data/materials/carbon-allotropes.json

Added allotropes of carbon from wikipedia

Added to carbon allotropes

---

data/geography/countries_with_capitals.json

I updated the name of the Kazakhstan capital as per https://github.com/dariusk/corpora/issues/346

updates Kazakhstan capital to Nur-Sultan

---

data/words/expletives.json

Given the other words (and many variations) included in the file, I believe 'cuck' would be considered an expletive.

Add 'cuck' to expletives.json

---

README.md

It's a free tier glitch.com app, because coleww's heroku app is down.
I'd be more than happy to take PRs on [github](https://github.com/jkirchartz/corpora-api) or add people to the project on [glitch](https://glitch.com/edit/#!/corpora-api)
(closes #370)

Add link to live corpora-api

---

data/words/verbs.json

I'm using this list of verbs to validate PR titles, I've found that some verbs are missing (particularly development related terms like "update", "merge",  "encode" etc...)
I hope these additions are helpful to someone out there 🙂

Add more verbs

---

data/colors/xkcd.json

added additional 5 colors 
darker blue
(#011288)
darker green
(#087804)
green again
(#16d43f)
darker purple
(#5f1b6b)
darker pink
(#c4387f)

Add missing xkcd colors

---

data/words/states_of_drunkenness.json

"inebriated"
